let products =[
    {
        name:"samsung galaxy s23",
        price: 1300,
        category:"phone",
        color:"black",  
        brand:"samsung",
        memory: "128gb",
        stock:100,
    },
    {
        name:"iphone 14 pro",
        price: 1500,
        category:"phone",
        color:"purple",
        brand:"apple",
        memory: "256gb",
        stock:50,

    },
    {
        name:"Ipad pro",
        price: 1200,
        category:"tablet",
        color:"white",
        brand:"apple",
        memory: "128gb",
        stock:20,
    },
    {
        name:"samsung galaxy tab s8",
        price: 900,
        category:"tablet",
        color:"black",
        brand:"samsung",
        memory: "128gb",
        stock:30,
    },
    {
        name:"samsung galaxy watch 5",
        price: 400,
        category:"watch",
        color:"black",
        brand:"samsung",
        memory: "16gb",
        stock:100,
    },
    {
        name:"apple watch series 8",
        price: 500,
        category:"watch",
        color:"white",
        brand:"apple",
        memory: "16gb",
        stock:50,
    },
    {
        name:"samsung galaxy buds 2",
        price: 200,
        category:"earphone",
        color:"black",
        brand:"samsung",
        memory: "16gb",
        stock:100,
    },
    {
        name:"apple airpods pro",
        price: 250,
        category:"earphone",
        color:"white",
        brand:"apple",
        memory: "16gb",
        stock:50,
    },
    {
        name:"samsung galaxy book 3",
        price: 2000,
        category:"laptop",
        color:"black",
        brand:"samsung",
        memory: "512gb",
        stock:20,
    },
    {
        name:"macbook pro 2023",
        price: 2500,
        category:"laptop",
        color:"silver",
        brand:"apple",
        memory: "512gb",
        stock:10,
    },
    {
        name:"samsung galaxy z fold 4",
        price: 1800,
        category:"phone",
        color:"black",
        brand:"samsung",
        memory: "256gb",
        stock:50,
    },
    {
        name:"samsung galaxy z flip 4",
        price: 1600,
        category:"phone",
        color:"purple",
        brand:"samsung",
        memory: "256gb",
        stock:50,
    },
    {
        name:"samsung galaxy a54",
        price: 500,
        category:"phone",
        color:"black",
        brand:"samsung",
        memory: "128gb",
        stock:100,
    },
    {
        name:"iphone 14",
        price: 1000,
        category:"phone",
        color:"black",
        brand:"apple",
        memory: "128gb",
        stock:50,
    },
    {
        name:"samsung galaxy a34",
        price: 400,
        category:"phone",
        color:"black",
        brand:"samsung",
        memory: "128gb",
        stock:100,
    },
    {
        name:"samsung galaxy a14",
        price: 300,
        category:"phone",
        color:"black",
        brand:"samsung",
        memory: "128gb",
        stock:100,
    },
    {
        name:"iphone 13 pro",
        price: 1200,
        category:"phone",
        color:"black",
        brand:"apple",
        memory: "256gb",
        stock:50,
    },
    {
        name:"samsung galaxy s22",
        price: 1000,
        category:"phone",
        color:"black",
        brand:"samsung",
        memory: "128gb",
        stock:100,
    },
    {
        name:"samsung galaxy s21 fe",
        price: 800,
        category:"phone",
        color:"black",
        brand:"samsung",
        memory: "128gb",
        stock:100,
    },
    {
        name:"samsung galaxy s20 fe",
        price: 700,
        category:"phone",
        color:"black",
        brand:"samsung",
        memory: "128gb",
        stock:100,
    },
]

let user = {
    username:"admin",
    password:"admin123",
}

for(let i = 0;i<products.length;i++){
    if(products[i].brand=="apple"){
        console.log(products[i].name + " is an apple product")
    }
    else{
        console.log(products[i].name,"bular samsung producti");
    }
    
}
